// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aiiekcvptisdoiawakjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpaWVrY3ZwdGlzZG9pYXdha2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjAyNDksImV4cCI6MjA3Mjg5NjI0OX0.NMdDLxHnQd4ZV3hzxWxodRtiFw1IEyZvfa4pWVvNf58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});